package main;

// Class to hold instances of Line Mappings generated by Step2

public class UnchangedLMap {
    int oldIndex;
    int newIndex;

    public UnchangedLMap(int oldIndex, int newIndex){
        this.oldIndex = oldIndex;
        this.newIndex = newIndex;
    }
    

}
